# Generated by Django 6.0.6 on 2026-06-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('level', models.CharField(choices=[('business_kpi', 'Business KPI'), ('kpi', 'KPI'), ('metric', 'Metric')], max_length=50)),
                ('kpi_type', models.CharField(blank=True, choices=[('behavioral', 'Behavioral'), ('experience', 'Experience'), ('operational', 'Operational'), ('n_a', 'n.a.')], default='', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('why_important', models.TextField(blank=True)),
                ('do_we_measure_it', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partially', 'Partially')], default='no', max_length=20)),
                ('how_measure_it', models.TextField(blank=True)),
                ('where_store', models.CharField(blank=True, max_length=300)),
                ('review_cadence', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='', max_length=20)),
                ('influences', models.TextField(blank=True)),
                ('initiatives', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('lifecycle_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='journey.phase')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='journey.step')),
            ],
            options={
                'ordering': ['level', 'lifecycle_phase__order', 'kpi_type', 'name'],
            },
        ),
    ]
