# Generated by Django 6.0.6 on 2026-06-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='journey_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='journey.journeyphase'),
        ),
    ]
