# Generated by Django 6.0.6 on 2026-06-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_kpi_journey_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='effort',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = least effort, 5 = most effort', null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='impact',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = lowest, 5 = highest', null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='implementation_phase',
            field=models.CharField(choices=[('defined', '1. Defined'), ('data_sourced', '2. Data sourced'), ('instrumented', '3. Instrumented'), ('actively_reviewed', '4. Actively reviewed')], default='defined', max_length=30),
        ),
        migrations.AddField(
            model_name='kpi',
            name='target_quarter',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
