# Generated by Django 6.0.6 on 2026-06-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_kpi_effort_kpi_impact_kpi_implementation_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='contributes_to',
            field=models.ManyToManyField(blank=True, help_text='Higher-level KPIs this KPI contributes to', related_name='supported_by', to='kpi.kpi'),
        ),
    ]
