# Generated by Django 6.0.6 on 2026-06-23 14:30

from django.db import migrations, models


def convert_impact_effort(apps, schema_editor):
    KPI = apps.get_model('kpi', 'KPI')
    for kpi in KPI.objects.all():
        # Convert impact: null/blank → '', 1-3 → low, 4-5 → high
        try:
            impact_val = int(kpi.impact) if kpi.impact not in (None, '') else None
        except (ValueError, TypeError):
            impact_val = None

        if impact_val is None:
            kpi.impact = ''
        elif impact_val <= 3:
            kpi.impact = 'low'
        else:
            kpi.impact = 'high'

        # Convert effort: null/blank → '', 1-2 → low, 3-5 → high
        try:
            effort_val = int(kpi.effort) if kpi.effort not in (None, '') else None
        except (ValueError, TypeError):
            effort_val = None

        if effort_val is None:
            kpi.effort = ''
        elif effort_val <= 2:
            kpi.effort = 'low'
        else:
            kpi.effort = 'high'

        kpi.save(update_fields=['impact', 'effort'])


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_kpi_contributes_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='effort',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='impact',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low')], default='', max_length=4),
        ),
        migrations.RunPython(convert_impact_effort, migrations.RunPython.noop),
    ]
