# Generated by Django 6.0.6 on 2026-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_impact_effort_high_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='roadmap_order',
            field=models.IntegerField(default=0),
        ),
    ]
