# Generated by Django 6.0.6 on 2026-06-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_roadmap_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='measurement_current',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='measurement_target',
            field=models.TextField(blank=True),
        ),
    ]
