# Generated by Django 6.0.6 on 2026-06-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_split_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='measurement_trigger',
            field=models.CharField(blank=True, choices=[('fixed_interval', 'Fixed interval'), ('after_event', 'After event')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='kpi',
            name='measurement_trigger_detail',
            field=models.TextField(blank=True),
        ),
    ]
