# Generated by Django 6.0.6 on 2026-06-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0008_measurement_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='influences',
        ),
    ]
