# Generated by Django 6.0.6 on 2026-06-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0009_remove_influences'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='store_current',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='kpi',
            name='store_target',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
