# Generated by Django 6.0.6 on 2026-06-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0010_store_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='monitoring_cadence',
            field=models.CharField(blank=True, choices=[('continuously', 'Continuously / Real-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='', max_length=20),
        ),
    ]
